spring:
  application:
    name: listplus-api-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/listplus_api_user}
    username: ${DB_USERNAME:listplus}
    password: ${DB_PASSWORD:listplus}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    jpa:
      repositories:
        enabled: true

kafka:
  broker:
    host: ${KAFKA_BROKER_HOST:localhost}
    port: ${KAFKA_BROKER_PORT:9092}
  topics:
    user: ${KAFKA_BROKER_USERS_TOPIC:users}
  groups:
    user: ${KAFKA_BROKER_USERS_GROUP:users}

server:
  port: 8081
  servlet:
    context-path: /listplus-api-user-service/v1