spring:
  application:
    name: listplus-api-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LISTPLUS_API_USER_DB_URL:jdbc:mysql://localhost:3306/listplus_api_user}
    username: ${LISTPLUS_API_USER_DB_USERNAME:listplus}
    password: ${LISTPLUS_API_USER_DB_PASSWORD:listplus}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    jpa:
      repositories:
        enabled: true

kafka:
  broker:
    host: localhost
    port: 29092
  topics:
    user: users
  groups:
    user: users

server:
  port: 8081
  servlet:
    context-path: /listplus-api-user-service/v1